# Generated by Django 2.2.6 on 2019-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beta_tester',
            field=models.BooleanField(default=False),
        ),
    ]
