# Generated by Django 2.2.6 on 2019-10-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191011_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Cancelamento'),
        ),
    ]
