# Generated by Django 3.0.5 on 2020-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='status',
            new_name='ativo',
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
