# Generated by Django 3.0.5 on 2020-04-22 22:35

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Canditado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('position', models.IntegerField(blank=True, default=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image)),
                ('votos', models.IntegerField(default=1)),
                ('text', models.TextField()),
                ('cor', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nome')),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Status')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FanPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=800, null=True, verbose_name='Link')),
                ('relevance', models.CharField(max_length=10)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('cidade', models.CharField(blank=True, default='Patrocínio', max_length=255, null=True)),
                ('agendamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('default_content', models.BooleanField(blank=True, default=False)),
                ('enable_comment', models.BooleanField(blank=True, default=True)),
                ('shared', models.BooleanField(blank=True, default=True)),
                ('championship', models.BooleanField(blank=True, default=False)),
                ('summary', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('nome_programa', models.CharField(blank=True, max_length=255, null=True)),
                ('ao_vivo', models.BooleanField(blank=True, default=False)),
                ('busca', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image)),
                ('access_number', models.IntegerField(blank=True, default=1, null=True)),
                ('position', models.IntegerField(blank=True, default=1, null=True)),
                ('total_comments', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('id_externo', models.IntegerField(blank=True, editable=False, null=True)),
                ('posicao_banner', models.IntegerField(blank=True, null=True)),
                ('posicao_outra_noticia', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('position', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('text', models.TextField()),
                ('video', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image)),
                ('positive', models.IntegerField(default=1, editable=False)),
                ('negative', models.IntegerField(default=0, editable=False)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.New')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('secao', models.CharField(max_length=80)),
                ('slug', models.CharField(max_length=100)),
                ('position', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vereador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=300)),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Opcao')),
            ],
        ),
        migrations.CreateModel(
            name='OutraNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('position', models.IntegerField(blank=True, default=1, null=True)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.New')),
            ],
        ),
    ]
